### ISSUE TITLE
Improve re-using channels

### ISSUE THREAD

**Issue by palkan** [anycable/anycable-client#11]
There is common pattern to subscribe to the same channel from multiple independent _components_. For example:

```js
// component-one.js
import cable from 'cable'
import { ChatChannel } from 'channels/chat'

// Build an instance of a ChatChannel class.
const channel = new ChatChannel({ roomId: '42' })

// Subscribe to the server channel via the client.
await cable.subscribe(channel)

channel.on('message', msg => console.log("component one received message", `${msg.name}: ${msg.text}`))

// component-two.js
import cable from 'cable'
import { ChatChannel } from 'channels/chat'

// Build an instance of a ChatChannel class.
const channel = new ChatChannel({ roomId: '42' })

// Subscribe to the server channel via the client.
await cable.subscribe(channel)

channel.on('message', msg => console.log("component two received message", `${msg.name}: ${msg.text}`))
```

We cannot build multiple instances with the equal identifiers—that would result in a server side error during the subscription. 
If we extract a ChatChannel instance into its own module (easy), we still have a problem with calling potentially calling `cable.subscribe(channel)` multiple times. 

The short term proposal is to make `cable.subscribe(channel)` idempotent (similarly to `cable.connect()`).

The long term proposal is to provide an additional abstraction to _memoize_ channel instances, so we can do the following:

```js
const channel = cable.fetchChannel(ChatChannel, { roomId: '42' })
```

**Comment by lokkirill** [comment]
Added new [PR#13](https://github.com/anycable/anycable-client/pull/13) to fix parallel connection of different channels
