### ISSUE TITLE
Why isn't @hotwired/turbo a turbo-stream package dependency?

### ISSUE THREAD

**Issue by yenshirak** [anycable/anycable-client#23]
@hotwired/turbo is imported here:
https://github.com/anycable/anycable-client/blob/master/packages/turbo-stream/stream_source_element.js#L1

**Comment by palkan** [comment]
Oh, it should be there. As a peer dependency, I think. Will add.

**Comment by palkan** [comment]
Fixed and released as `@anycable/turbo-stream` 0.2.1

**Comment by yenshirak** [comment]
Great, thanks
