### ISSUE TITLE
No subscription ack received in 5000ms, retrying. Stale connection

### ISSUE THREAD

**Issue by kushniryb** [anycable/anycable-client#27]
Hi folks! 

Let me start off by saying that I'm not sure if this issue is related to the library itself and if not - apologies for wasting your time. That said, I'd really appreciate it if you could point me in the right direction when it comes to debugging the issue I'm facing.

I'm using AnyCable client as a replacement for `@rails/actioncable` package in conjunction with Rails. I'm **NOT** using AnyCable on the backend yet (we're just testing the waters at this point). 
The application is hosted on Heroku alongside PSQL & Redis Green. There's a group chat written in React that establishes AC connection when you click on one of the groups (React component)
```jsx
import { createConsumer } from "@anycable/web";

useEffect(() => {
  const cable = createConsumer();
  const subscription = cable.subscriptions.create(channelConfig, { 
    connected: () => {
      // fetchMessages, do other things
    },
  });
  return () => { cable.subscriptions.remove(subscription) }
}, [])
```
It seems to work great but sometimes I'm seeing the following messages in the console:
```
no subscription ack received in 5000ms, retrying subscribe {"channel":"Chat::ChannelsChannel","id":19}
Stale connection: 7965ms without pings
```
It can take from 2 to 20-30 seconds to obtain subscription confirmation. 
I've also noticed that it's a bit easier to replicate if I visit a page, open a chat, issue a hard refresh and open the chat again although it's not a reliable replication scenario.

The backend implementation of `Chat::ChannelsChannel` is quite basic:
```ruby
module Chat
  class ChannelsChannel < ApplicationCable::Channel
    def subscribed
      channel = Channel.find_by(id: params[:id])
      return reject unless allow_subscription_for?(channel)

      stream_for(channel)
    end

    def unsubscribed
      channel = Channel.find_by(id: params[:id])
      return if channel.nil?

      stop_stream_for(channel)
    end
  end
end
```

My initial assumption is that a web-socket connection from the previous visit is not closed in time which causes server not to acknowledge a new subscription but I'm not sure how realistic that is. 
I was also thinking it could be related to the lack of resources (ActionCable seems to struggle with large number of connections) but we have only 3-4 users testing it at the same time.

Have you encountered anything similar before?

Thanks in advance and thank you for your hard work! ❤️

**Comment by palkan** [comment]
Hey!

> no subscription ack received in 5000ms...
Stale connection: 7965ms without pings

Looks like the Action Cable's executor (a pool of threads) is under pressure and cannot process message on time. It should send pings every 3s, but here we see the log message indicating that no pings were received in 8s — that's a lot. I only see such numbers when I perform benchmarks 🙂

What's the number of consumed and broadcasted message per a period of time? Action Cable uses just 4 threads by default to process and send messages; maybe, you're sending so many, that it can't catch up with the pace 🤷‍♂️. You can try increasing this number by setting `config.action_cable.worker_pool_size` to a higher value. Or, maybe, it's time to consider AnyCable 😉

P.S. Closing the issues since it doesn't seem related to the client. But feel free to ask any additional questions, we'll be glad to help.

**Comment by kushniryb** [comment]
Hey @palkan, hope you are well! 
I'm facing a similar issue once again and was hoping you could point me in the right direction 🙂

**Brief overview of our setup** 
Rails 7.0.7 on Heroku with Puma. Number of Puma workers is set to 6. DB pool is set to 40. We run a dedicated Redis instance for AC / Turbo Streams, average number of pubsub channels is ~200 including internal AC streams. 

**Problem** 
Everything works fine for an hour or two following a dyno restart. Afterwards, we're getting a lot of stale connection and no ack received messages in the console. No issues with RAM nor CPU usage. Redis seems to be ok as well, no spikes at all. What's interesting about it is the fact that we get `confirmation_subscription` but no `ping` messages. The situation doesn't improve until another restart.

<img width="878" alt="Screenshot 2023-11-15 at 4 54 01 PM" src="https://github.com/anycable/anycable-client/assets/13320669/0c3872df-560f-4d83-9390-004f8cd4ceca">


**Things I've tried since the last time**
- Configured a separate Redis instance for ActionCable & Turbo Streams
- Switched from `@hotwired/turbo-rails` to `@anycable/turbo-stream`
- Switched from `@rails/actioncable to `@anycable/web`
- Added `action-cable-redis-backport`
- Increased `worker_pool_size` from `4` to `40`
- Tried different Redis providers on Heroku

We're still using `ActionCable` on the backend but our average load is quite small so naturally I'm perplexed as to what might be causing it. Could you please offer any advice?

Thanks in advance! ❤️

**Comment by palkan** [comment]
Thanks for the details!

Here is the code responsible for sending pings: https://github.com/rails/rails/blob/67bc7652fbf7134454acd0c1a02324687102c789/actioncable/lib/action_cable/server/connections.rb#L29

I see the following possible things that could go wrong here (in theory):

1) `event_loop` is overloaded with other tasks and fails to catch up with pings (NOTE: this is not a worker pool, it's a different one used to broadcast messages to clients, see https://speakerdeck.com/palkan/railsworld-2023-untangling-cables-and-demystifying-twisted-transistors?slide=72; do you by any chance perform tons of `broadcast` calls? 

2) There is a connection object that misbihaves and blocks the `beat` operation (which is just transmit, shouldn't be a problem); similarly, that blocking might occur during execution of broadcast callbacks. But as I understand, you use Turbo Streams, no custom `stream_from do .. end` stuff, right?

3) Finally, the connection may not added to the list of connections here: https://github.com/rails/rails/blob/67bc7652fbf7134454acd0c1a02324687102c789/actioncable/lib/action_cable/connection/base.rb#L191 That could happen if the `connect` call raise some unexpected exception. But that should prevent server form sending `welcome` messages, and we see them. So, looks like not our case.

In any case, I'd suggest patching the `#setup_heartbeat_timer` and `#add_connection` methods and add some logs to get more observability.

**Comment by kushniryb** [comment]
Thanks so much @palkan!
We're getting closer!

I've spent some time today testing these theories and here's what I've found:
1. We had one job producing ~30 broadcast calls. We temporarily disabled it but observed **_no_** changes to the aforementioned issue
2. That's correct, we don't use broadcast callbacks
3. We've added basic logging to `#setup_heartbeat_timer` and `#add_connection` methods as well as logs describing the state of pool executor. For context, we're running 6 puma workers so we had 6 log statements describing the state of each executor.  We've found out that AC starts misbehaving the moment puma issues a phased worker restart. Afterwards, we're left with one executor and a lot of idle connections. 

At the moment we're trying to figure out the best way to handle phased restarts / upgrades but if you have any ideas please let us know!

**Comment by kushniryb** [comment]
We've managed to resolve it! 

For anyone dealing with the same problem - if you're using Puma with `fork_worker` option make sure `fork_worker` value is set to `0` to disable phased restarts upon hitting a certain number of worker requests (1000 by default)

@palkan Thanks so much for your help, I appreciate it!
