### ISSUE TITLE
History Not Supported When Testing Resumability

### ISSUE THREAD

**Issue by Tripple-A** [anycable/anycable-client#32]
**Environment**
npm packages:
@anycable/turbo-stream @ 0.4.0
@anycable/core @ 0.7.12
@anycable/web @ 0.7.3

**AnyCable-Go version:**
1.4.8
**AnyCable gem version:**
anycable-rails (1.4.3)
anycable (1.4.3)

**Application.js**
```javascript
import '@hotwired/turbo'
import { start } from '@anycable/turbo-stream'
import { createCable } from '@anycable/web'

start(createCable({ protocol: 'actioncable-v1-ext-json' }))
```
**Partial**
```ruby
<div id=<%= dom_id(message) %>> <%= message.content %> </div>
```

Index
```ruby
<%= turbo_stream_from "messages" %>
<div id="messages">
  <%= render @messages %>
</div>
```

**Error - History Not Supported**
```
WARN 2024-01-13T20:45:26.023Z context=node sid=YVQUVol2LVgiLGoYC-lWg Failed to handle incoming message '{"command":"subscribe","identifier":"{\"channel\":\"Turbo::StreamsChannel\",\"signed_stream_name\":\"ImJvb2tzIg==--7d6448fb141034dacfe0e78daf6fed7d6c1e95c39a740379b1fdf83cd29b5274\"}","history":{"since":1705178725,"streams":{}}}' with error: History not supported
```

**Expectation**
Resumability is possible.

**Actual Behaviour**
The `subscribe` command is called, the `reject_history` type of message is received. No messages sent during the "offline" state is received. The `since` param is properly set but the `streams` are an empty hash.

**Screenshots**

<img width="973" alt="Screenshot 2024-01-13 at 22 00 52" src="https://github.com/anycable/anycable-client/assets/52589264/b90aa261-fe4b-4bb9-8d76-929665408136">

<img width="773" alt="Screenshot 2024-01-13 at 22 01 31" src="https://github.com/anycable/anycable-client/assets/52589264/3fa57daa-236f-493a-be45-ec7ca48fe0b4">

**Question**
Are there any other configurations required for `History` to be supported when the AnyCable JS client is used with turbo streams?

Thank you!

**Comment by palkan** [comment]
Hey!

Looks like you haven't configured history support at the server-side (currently, it's opt-in). You should provide the broker configuration (see [docs](https://docs.anycable.io/anycable-go/reliable_streams?id=quick-start); the easiest way is to provide the `--presets=broker` option for `anycable-go`.

**Comment by Tripple-A** [comment]
I found the manual configuration to work just fine out of the box. Thank you! 

However, with the change to `redisx` adapter in the `yml` file and using the `--presets=broker` command, stream broadcasts do not work out of the box. Seems like changing the adapter alone is not sufficient and some extra configuration is needed.
The `subscribe` command message  is not handled and the gives the error: `Unknown epoch: BChC, current: uxX1`.

I checked the source code and updated my `yml` file to include the stream name which corresponds to the `redis_channel` as thus:

```yml
default: &default
  access_logs_disabled: false
  log_grpc: false
  broadcast_adapter: :redisx, { stream_name: "__anycable__" }
  redis_channel: "__anycable__"
  # redis_url: "redis://localhost:6379/1"
```

This works!

Maybe I missed something in the documentation as I found this also stated [here](https://github.com/anycable/anycable/blob/d9187318c4af104c543536e68477f592b5f32730/docs/configuration.md?plain=1#L50) in some way.
If NO, should we update the documentation to include this info in the [quick start](https://docs.anycable.io/anycable-go/reliable_streams?id=quick-start) section?

Thank you!

**Comment by palkan** [comment]
> With preset, the provider is set as http, instead of redisx, despite being stated in the yml file as redisx.

YAML config is only used by the Ruby library. And, yes, the `broker` preset makes no assumptions regarding Redis, so it configures the only dependency-free adapter, HTTP. RedisX must be always specified explicitly for now.
