### ISSUE TITLE
Testing support

### ISSUE THREAD

**Issue by palkan** [anycable/anycable-client#8]
Add ability to unit-test channels.

For example, by creating a test cable implementation.

## Example

Having a channel:

```js
import { Channel } from "@anycable/core";

class ChatChannel extends Channel {
  static identifier = "ChatChannel";

  async speak(message) {
    return this.perform("speak", { message });
  }

  async leave() {
    // some custom logic
    return this.disconnect();
  }
}
```

We would like to test it like this (using Jest):

```js
import { ChatChannel } from './channel.js';
import { TestCable } from '@anycable/core/testing';

describe('ChatChannel', () => {
  let channel: ChatChannel
  let cable: TestCable

  beforeEach(() => {
    cable = new TestCable();
    channel = new ChatChannel({ id: '2021' });
    cable.subscribe(channel);
  })

  it('speak perform an action', async () => {
    await channel.speak("hello");
    
    expect(cable.outgoing).toEqual([{message: "hello"}])
  })

  it('disconnects when leave', () => {
    await channel.leave()

    expect(channel.state).toEqual("disconnected");
  })
})
``

**Comment by palkan** [comment]
> what means by the ability to unit-test?)

See the example above: we want to make it possible to test channel classes in isolation (i.e., without actual WS connection or whatever).

**Comment by TheSeally** [comment]
@palkan, I have some questions about test implementation.
- should outgoing array stores action name or only payload (In the example above I see only payload)
- should test cable process any other events except disconnect (that is in example). I think other methods from channel could be executed directly by cable instance, but maybe I missed something
